### ISSUE TITLE
Make note of fix to "Cannot find cairo-pdf.h"

### ISSUE THREAD

**Issue by WetDesertRock** [ungerik/go-cairo#16]
In https://github.com/fogleman/ln/issues/5 JRov makes note that to fix build errors for xcode, you have to run `xcode-select --install`

**Comment by JanRuettinger** [comment]
I am receiving that error again even after running `xcode-select --install`. 

I have checked the pkg-config search directories with:
`pkg-config --list-all --debug 2>&1 > /dev/null |  grep 'Scanning directory'`
=> cairo-pdf.h header file is in search path
