### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by ARolek** [ungerik/go-cairo#9]
System specs:

- Centos6
- Go 1.4.2
- cairo.x86_64           - 1.8.8-6.el6_6
- cairo-devel.x86_64 - 1.8.8-6.el6_6

when I run go-cairo-example I get the following output:

```
could not determine kind of name for C.cairo_pdf_version_t
could not determine kind of name for C.cairo_pdf_version_to_string
```

**Comment by ungerik** [comment]
Sounds like you have an incompatible cairo version. Check if you can find "cairo_pdf_version_t" in the C headers.

**Comment by ARolek** [comment]
I just ran:

```
grep -rnw /usr/include/cairo/ -e "cairo_pdf_version_t"
```

the dir `/usr/include/cairo/` contains the following files:

```
/usr/include/cairo/cairo-deprecated.h
/usr/include/cairo/cairo-features.h
/usr/include/cairo/cairo-ft.h
/usr/include/cairo/cairo-pdf.h
/usr/include/cairo/cairo-ps.h
/usr/include/cairo/cairo-svg.h
/usr/include/cairo/cairo-version.h
/usr/include/cairo/cairo-xlib-xrender.h
/usr/include/cairo/cairo-xlib.h
/usr/include/cairo/cairo.h
```

The output was blank, so the string was not found. 

What version of Cairo do these bindings work with?

**Comment by ungerik** [comment]
I am using libcairo2-dev version: 1.13.0~20140204-0ubuntu1.1 which is the standard on Ubuntu 14.10. Seems you have to upgrade from 1.8 to 1.13 or 1.14.

**Comment by ungerik** [comment]
Solution: Update to latest cairo version.

**Comment by ARolek** [comment]
Great. Thanks for the help. Centos6's yum repo is really out of date.
